UI.MVC/Models/Ideas/IdeaVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Net;
using System.Xml.Linq;
using Domain;
using System.Web;
using D.UI.MVC.Models.Fields;
using Microsoft.AspNetCore.Http;

namespace D.UI.MVC.Models.Ideas
{
  /*  public static class IdeaExtensions
    {
        public static IdeaViewModel ToViewModel(this Idea idea)
        {
            var model = new IdeaViewModel
            {
                ideaViewModelId = idea.ideaId,
                
                
            };
        }
    }*/
    public class IdeaVM
    {
        public int ideationId { get; set; }
        public String[] ideationQuestion { get; set; }
        
        public int ideaViewModelId { get; set; }
        public string name { get; set; }
      //  public ICollection<FieldViewModel> fields { get; set; }
        public TextFieldVm textFieldVM { get; set; }
        public ImageFieldVm imageFieldVM { get; set; }
        public VideoFieldVm videoFieldVM { get; set; }
        public MapFieldVm    mapFieldVM { get; set; }
        

        
    //  public FieldViewModel fieldViewModel { get; set; }
    
    
        
        
    }

   
    
    
        
}

UI.MVC/Controllers/Api/ProjectsController.cs
using System.Collections.Generic;
using BL;
using D.UI.MVC.Models;
using Domain;
using Microsoft.AspNetCore.Mvc;

namespace D.UI.MVC.Controllers.Api
{
    public class ProjectsController : Controller
    {
        IProjectManager mgr = new ProjectManager();
        
        [HttpGet("/api/Projects")]
        public IActionResult GetProjects()
        {
            IEnumerable<Project> projects = mgr.getProjects();
            List<ProjectRESTModel> newProjects = new List<ProjectRESTModel>();
            foreach (var project in projects)
            {
                ProjectRESTModel newProject = new ProjectRESTModel()
                {
                    projectId = project.id,
                    name = project.name
                };
                newProjects.Add(newProject);
            }
            return Ok(newProjects);
        }
        
        [HttpGet("/api/Projects/{id}")]
        public IActionResult GetProject(int id)
        {
            //Either you add a service in startup.cs to ignore reference loop handling
            //or you comment/delete the 'include' line in the project repository
            Project project = mgr.getProject(id);
            return Ok(project);
        }
    }
}

UI.MVC/Controllers/IdeaController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BL;
using D.UI.MVC.Models.Ideas;
using Domain;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace D.UI.MVC.Controllers
{
    public class IdeaController : Controller
    {
        private IIdeationManager ideationMgr;
        public IdeaController()
        {
            ideationMgr = new IdeationManager();
        }
        public IActionResult CreateIdeaPage(int ideationId)
        {
            
            IdeationQuestion[] ideationQuestions = ideationMgr.GetIdeationQuestions(ideationId).ToArray();
            IdeaVM ideaVm = new IdeaVM();


            String[] questions = new string[ideationQuestions.Length];

            for (int i = 0; i < ideationQuestions.Length; i++)
            {
                    questions[i] = ideationQuestions[i].question;

            }

            ideaVm.ideationQuestion = questions;
            ideaVm.ideationId = ideationId;
                
      
          
            
            return View(ideaVm);
        }

        public IActionResult MapInput()
        {
            return View();
        }
            


        public IActionResult CreateIdea(IdeaVM ideaVm)
        {
            Idea idea = new Idea();
            ICollection<Field> fields = new List<Field>();
            TextField textField = new TextField();
            ImageField imageField = new ImageField();
            VideoField videoField = new VideoField();
            MapField mapField = new MapField();

            textField.text = Convert.ToString(ideaVm.textFieldVM.text);
            mapField.latitude = ideaVm.mapFieldVM.latitude;
            mapField.longitude = ideaVm.mapFieldVM.longitude;

            using (MemoryStream memoryStream = new MemoryStream())
            {
                ideaVm.imageFieldVM.imageFile.CopyTo(memoryStream);
                imageField.imageData = memoryStream.ToArray();
            }
            using (var reader = ideaVm.imageFieldVM.imageFile.OpenReadStream())
            using (var stream = new MemoryStream())
            {
                {    
                   reader.CopyTo(stream);
                   imageField.imageData = stream.ToArray();

                }    
                                        
            }
            using (var reader = ideaVm.videoFieldVM.videoFile.OpenReadStream())
            using (var stream = new MemoryStream())
            {
                {    
                    reader.CopyTo(stream);
                    videoField.videoData = stream.ToArray();

                }    
                                        
            }

            Ideation ideation = ideationMgr.getIdeation(ideaVm.ideationId);

            idea.ideation = ideation;
            fields.Add(textField);
            fields.Add(imageField);
            fields.Add(videoField);
            fields.Add(mapField);
            idea.fields = fields;
            ideationMgr.createIdea(idea);

            var projectId = ideationMgr.getIdeation(ideaVm.ideationId).project.projectId;
            
            


            return RedirectToAction("Project" , "Project" , new { id= projectId });
        }
        

      
    }
    
}

UI.MVC/Controllers/ProjectController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using BL;
using D.UI.MVC.Models;
using Domain;
using Microsoft.AspNetCore.Mvc;

namespace D.UI.MVC.Controllers
{
    public class ProjectController : Controller
    {
        private IProjectManager projectMgr;
        private IIdeationManager ideationMgr;
        
        public ProjectController()
        {
            projectMgr = new ProjectManager();
            ideationMgr = new IdeationManager();
        }
       
        public IActionResult Index()
        {
            IEnumerable<Project> allProjects = projectMgr.getProjects();
            return View(allProjects);
        }

        public IActionResult Project(int id)
        {
            Project p1 = projectMgr.getProject(id);
            IEnumerable<IdeationQuestion> ideationQuestions1 = ideationMgr.GetIdeationQuestionsForProject(id);
            var model = new ProjectAndQuestions() {ideationQuestions = ideationQuestions1, project = p1};

            return View(model);
        }

        public IActionResult Ideas(int id)
        {
            IEnumerable<Idea> ideas = ideationMgr.getIdeas(id);
            return View(ideas);
        }

        public IActionResult MapTest()
        {
            return View();
        }
     
        
        
        
        public ActionResult ImageTest()
        {
            Idea idea = ideationMgr.getIdea(19);
           // Field[] fields = idea.fields.ToArray();
           var fields = idea.fields.ToArray();
           ICollection<ImageField> imageFields = new List<ImageField>();
           
           foreach (var imagefield in fields)
           {
             imageFields.Add((ImageField)imagefield);
           }
          
            return View(imageFields);
        }
    }
}

UI.MVC/Controllers/QuestionnaireController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using BL;
using D.UI.MVC.Models;
using Domain;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuestionUser = Domain.QuestionUser;

namespace D.UI.MVC.Controllers
{
    public class QuestionnaireController : Controller
    {
        private readonly IQuestionnaireManager qmgr;
        private readonly IProjectManager pmgr;

        public QuestionnaireController()
        {
            qmgr = new QuestionnaireManager();
            pmgr = new ProjectManager();
        }
        
        public IActionResult Questionnaires(int projectId)
        {
            IEnumerable<Questionnaire> allQuestionnaires = qmgr.getQuestionnaires(projectId);
            return View(allQuestionnaires);
        }
        
        public IActionResult Questionnaire(int questionnaireId)
        {
            FillInQuestionnaireModel fillInQuestionnaireModel = new FillInQuestionnaireModel();
            fillInQuestionnaireModel.questions = qmgr.getQuestions(questionnaireId);
            fillInQuestionnaireModel.questionnaire = qmgr.getQuestionnaire(questionnaireId);
            return View(fillInQuestionnaireModel);
        }

        public IActionResult CreateQuestionnairePage(int projectId)
        {
            QuestionnaireQuestion combinedModel = new QuestionnaireQuestion();
            combinedModel.projectId = projectId;
            return View(combinedModel);
        }

        public IActionResult ShowResultsPage(int questionnaireId)
        {
            QuestionResultModel combinedModel = new QuestionResultModel();
            IList<QuestionUser> questionUsers = new List<QuestionUser>();
            IList<string> answers = new List<string>();
            IList<Question> ques = new List<Question>();
            IList<OptionsAmount> optionsAmounts = new List<OptionsAmount>();
            combinedModel.questionnaire = qmgr.getQuestionnaire(questionnaireId); 
            
            foreach (var qu in qmgr.getQuestionUsers(questionnaireId))
            {
                questionUsers.Add(qu);
            }

            if (questionUsers.Count == 0)
            {
                return View(combinedModel);
            }
            combinedModel.questionUsers = questionUsers;
            var questionnaireAnswerCount = combinedModel.questionUsers.GroupBy(q => q.Question.id).ToList()[0].Count();
            combinedModel.answeredQuestionAmount = questionnaireAnswerCount;

            foreach (var qu in combinedModel.questionUsers)
            {
                Question q = qu.Question;
                if (q.questionType == QuestionType.DROPDOWN || q.questionType == QuestionType.RADIO_BUTTON)
                {
                    IList<Option> op = qmgr.getOptions(q.id).ToList();
                    foreach (var o in op)
                    {
                        if (o.option == qu.Answer)
                        {
                            answers.Add(o.id + "-" + o.question.id);
                        }
                    }
                }
                if (q.questionType == QuestionType.CHECK_BOX)
                {
                    IList<Option> op = qmgr.getOptions(q.id).ToList();
                    foreach (var o in op)
                    {
                        var parts = qu.Answer.Split(",");
                        foreach (var part in parts)
                        {
                            if (part == o.option)
                            {
                                answers.Add(o.id + "-" + o.question.id);
                            }
                        }
                    }
                }
            }

            foreach (var q in qmgr.getQuestions(questionnaireId))
            {
                if (q.questionType == QuestionType.DROPDOWN || q.questionType == QuestionType.RADIO_BUTTON || q.questionType == QuestionType.CHECK_BOX)
                {
                    foreach (var o in q.options)
                    {
                        q.options.Append(o);
                    }
                    ques.Add(q);
                }
            }
            var amountVotedPerQuestion = answers.GroupBy(o => o);
            foreach (var o in amountVotedPerQuestion)
            {
                var parts = o.Key.Split("-");
                OptionsAmount oa = new OptionsAmount()
                {
                    optionId = Convert.ToInt32(parts[0]),
                    questionId = Convert.ToInt32(parts[1]),
                    count = o.Count()
                };
                optionsAmounts.Add(oa);
            }

            combinedModel.optionsAmounts = optionsAmounts;
            combinedModel.questions = ques;
            
            return View(combinedModel);
        }

        public IActionResult EditQuestionnairePage(int questionnaireId)
        {
            QuestionnaireQuestion combinedModel = new QuestionnaireQuestion();
            combinedModel.questionnaire = qmgr.getQuestionnaire(questionnaireId);
            combinedModel.questions = qmgr.getQuestions(questionnaireId);
            return View(combinedModel);
        }

        public IActionResult DeleteQuestionnairePage(int questionnaireId)
        {
            Questionnaire questionnaire = qmgr.getQuestionnaire(questionnaireId);
            return View(questionnaire);
        }

        [HttpPost]
        public IActionResult EditQuestionnaire(IFormCollection form)
        {
            var oldQuestionnaireId = 0;
            var oldQuestionnaireName = "";
            ICollection<String> questionOptionKey = new List<string>();
            ICollection<String> questionOptionValue = new List<string>();
            
            foreach (var key in form.Keys)
            {
                if (key == "questionnaire.id")
                {
                    oldQuestionnaireId = Convert.ToInt32(form[key]);
                }
            }
            IList<QuestionUser> questionUsers = qmgr.getQuestionUsers(oldQuestionnaireId).ToList();
            foreach (var qu in questionUsers)
            {
                qmgr.removeQuestionUser(qu.id);
            }
            
            ICollection<int> notRemovedQuestionIds = new List<int>();
            Questionnaire oldQuestionnaire = qmgr.getQuestionnaire(oldQuestionnaireId);
            ICollection<Question> oldQuestions = qmgr.getQuestions(oldQuestionnaireId).ToList();

            foreach (var key in form.Keys)
            {
                if (key.StartsWith("question.question"))
                {
                    Question q = new Question()                    
                    {                                              
                        question = "",                      
                        questionnaire = oldQuestionnaire,          
                        questionType = QuestionType.OPEN_QUESTION, 
                        IotSetup = null,                           
                        options = new List<Option>()               
                    };
                    IList<Option> newOptions = new List<Option>();
                    string[] parts = key.Split("-");
                    int optionAmount = 1;
                    foreach (var subKey in form.Keys)
                    {
                        if (subKey == "dynamicFieldset" + parts[1])                                             
                        {        
                            if (form[subKey] == "email") { q.questionType = QuestionType.MAILADDRESS; }       
                            if (form[subKey] == "dropdown") { q.questionType = QuestionType.DROPDOWN; }         
                            if (form[subKey] == "radiobutton") { q.questionType = QuestionType.RADIO_BUTTON; }  
                            if (form[subKey] == "checkbox") { q.questionType = QuestionType.CHECK_BOX; }        
                            if (form[subKey] == "textarea") { q.questionType = QuestionType.OPEN_QUESTION; } 
                        }
                        if (subKey == "question.options-" + optionAmount + "-" + parts[1] + "-0")
                        {
                            Option o = new Option()
                            {
                                option = form[subKey],
                                question = q
                            };
                            newOptions.Add(o);
                            optionAmount++;
                        }
                    }
                    q.question = form[key];
                    qmgr.addQuestion(q);                           
                    qmgr.changeQuestionnaire(oldQuestionnaire);    
                    foreach (var o in newOptions)
                    {
                        qmgr.addOption(o.option, o.question);
                    }
                    q.options = newOptions;
                    qmgr.changeQuestion(q);
                }    
                if (key.StartsWith("question.options-"))         
                {
                    questionOptionKey.Add(key);                  
                    questionOptionValue.Add(form[key]);          
                }
            }
            foreach (var key in form.Keys)
            {
                if (key == "questionnaire.name")
                {
                    oldQuestionnaireName = form[key];
                }
                if (key.StartsWith("question-"))
                {
                    string[] parts = key.Split("-");
                    notRemovedQuestionIds.Add(Convert.ToInt32(parts[1]));
                    int testt = 1;
                    for (var i = 0; i < oldQuestions.Count; i++)
                    {
                        if (Convert.ToInt32(parts[1]) == oldQuestions.ToList()[i].id)
                        {
                            Question q = oldQuestions.ToList()[i];
                            q.question = form[key];

UI.MVC/Views/Project/CreateProjectPage.cshtml
@using Microsoft.Web.Mvc.Controls
@model D.UI.MVC.Models.Projects.ProjectVM

<body>
    <form asp-controller="Project" asp-action="CreateProject" method="post" enctype="multipart/form-data">

        <section id="contact" class="py-3">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <div class="card p-4 bg-dark">
                            <div class="card-body">
                                <h3 class="text-center text-light">Create a project</h3>
                                <hr>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input asp-for="name" type="text" class="form-control" placeholder="Title" />
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.EditorFor(x => x.imageFieldVM)
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input asp-for="startDate" type="date" class="form-control" placeholder="Start date" />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input asp-for="endDate" type="date" class="form-control" placeholder="End date" />
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input asp-for="description" type="text" textarea class="form-control" placeholder="Description" />
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    @Html.EditorFor(x => x.mapFieldVM)
                                </div>

                                <h3 class="text-center text-light">Phases</h3>
                                <hr>
                                <label asp-for="name">Name: </label>
                                <label asp-for="description">Description: </label>
                                <label asp-for="startDate">Start Date: </label>
                                <label asp-for="endDate">End Date: </label>
                                
                                <div class="text-dark" id="phaseList">


                                </div>

                                <input type="button" name="addRow" id="addRow" value="Click" class="btn bg-success btn-sm">
                                <input type="submit" value="Submit" class="btn bg-success btn-sm">
                            </div>
                    </div>
                </div>
            </div>
                </div>
        </section>


    </form>

</body>
<script type="text/javascript">

    $("#addRow").click(function () {

        var rowCount = $('.phaseRow').length;
        var inputString = "";

        inputString += '<td><input name="Phases[' + rowCount + '].name" type="text" class="nameType"/></td>';
        inputString += '<td><input name="Phases[' + rowCount + '].description" type="text" class="descriptionType"/></td>';
        inputString += '<td><input name="Phases[' + rowCount + '].startDate" type="date" class="startDateType"/></td>';
        inputString += '<td><input name="Phases[' + rowCount + '].endDate" type="date"  class="endDateType"/></td>';
        inputString += '<a href="javascript:void(0);" class="remRow">Remove</a>';
        $("#phaseList").append('<div class="phaseRow">' + inputString + '</div>');
        //            inputString += '<input name="Phases[' + rowCount + '].name" type="text" class="nameType"/>';
        //            inputString += '<input name="Phases[' + rowCount + '].description" type="text" class="descriptionType" />';
        //            inputString += '<input name="Phases[' + rowCount + '].startDate" type="date" class="startDateType"/>';
        //            inputString += '<input name="Phases[' + rowCount + '].endDate" type="date"  class="endDateType"/>';
        //            inputString += '<a href="javascript:void(0);" class="remRow">Remove</a>';
        //            $("#phaseList").append('<div class="phaseRow">' + inputString + '</div>');
        document.getElementsByName('nameType')[0].placeholder="Name"

    });

    $("#phaseList").on('click', '.remRow', function () {

        (this).closest(".phaseRow").remove();

        $('.nameType').each(function (index) {
            $(this).attr('name', 'Phases[' + index + '].name');
        });

        $('.descriptionType').each(function (index) {
            $(this).attr('name', 'Phases[' + index + '].description');
        });

        $('.startDateType').each(function (index) {
            $(this).attr('name', 'Phases[' + index + '].startDate');
        });

        $('.endDateType').each(function (index) {
            $(this).attr('name', 'Phases[' + index + '].endDate');
        });
    });

    

</script> 9 

<!--<link rel="stylesheet" href="~/css/CreatePage.css"> -->

UI.MVC/Views/Project/Idea.cshtml
@using Domain
@model IdeaAndAnswers

@foreach (var item in @Model.ideationQuestions)
{
    @Html.DisplayFor(modelItem => item.question)
}
<h1>Your Idea !</h1>

<table class="table">
    <tr>
        <th>
            <p>Title</p>
        </th>

        <th>
            <p>Content</p>
        </th>
        
        <th>User</th>


    </tr>
   
    
        
    <tr>
        <td>
            @Model.idea.title
        </td>
            
        <td>
            @Model.idea.title
        </td>
        <td>
            @Model.idea.user.firstName   
        </td>

    </tr>
    
</table>

<h1> Answers</h1>

<table class="table">
    
    <tr>
        <td>
            User
        </td>
        
        <td>
            Date
        </td>
        
        <td>
            content
        </td>
    </tr>

    @foreach (var item in @Model.answers)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.user)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.content)
            </td>

        </tr>


    }

</table>

UI.MVC/Views/Project/Ideas.cshtml
@model IEnumerable<Domain.Idea>

<h1>Projects</h1>

<table class="table">
    <tr>
        <th>
            <p>User</p>
        </th>
        <th>
            <p>Title</p>
        </th>
        
        <th>Content</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.user.firstName.Substring(0,1).@Html.DisplayFor(modelItem => item.user.lastName)    
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.content)
            </td>
            <td><button onclick="showPopup(@item.ideaId)">Report</button></td>
        </tr>
    }
</table>

<div style="top: 0; bottom: 0; left: 0; right: 0; position: fixed; background-color: lightgrey; opacity: 0.7; display: none" id="blur" name="blur">
</div>
<div style="position: absolute; left: 50%; top: 50%; background-color: whitesmoke; width: 53%; height: 40%; transform: translate(-50%, -50%); display: none" id="popup" name="popup">
    <div name="popupContent" id="popupContent" style="height: 80%">
        <div name="inputArea" id="inputArea" style="width: 100%; height: 100%">
            <p style="text-align: center; padding: 10px; margin: 0px">Why do you want to report this post?</p>
            <div style="text-align: center; height: 70%">
                <textarea style="width: 90%; height: 100%; resize: none" id="reportText" name="reportText"></textarea>
            </div>
        </div>
        <div name="successMessage" id="successMessage" style="text-align: center; width: 100%; height: 100%; padding-top: 80px">
            <img src="/images/green_check.png" style="width: 50px; height: 50px"/>
            <p>Your report has been successfully submitted.</p>
        </div>
        <div name="failureMessage" id="failureMessage" style="text-align: center; width: 100%; height: 100%; padding-top: 80px">
            <img src="/images/red_cross.jpg" style="width: 50px; height: 50px"/>
            <p>Something went wrong, please try again later.</p>
        </div>
    </div>
    <div style="text-align: center; margin-bottom: 5px; height: 20%">
        <button style="margin-right: 10px" onclick="submitReport()" id="submitButton">Submit</button><button onclick="closePopup()">Close</button>
    </div>
</div>

<script type="text/javascript">
    var ideaId = 0;
    function showPopup(id) {
        ideaId = id;
        document.getElementById("popup").style.display = "block";
        document.getElementById("blur").style.display = "block";
        document.getElementById("inputArea").style.display = "block";
        document.getElementById("submitButton").style.display = "inline";
        closeSubmissionMessage();
    }
    
    function closePopup() {
        document.getElementById("popup").style.display = "none";
        document.getElementById("blur").style.display = "none";
        document.getElementById("reportText").value = "";
        closeSubmissionMessage();
    }
    
    function submitReport() {
        var reportMessage = $('#reportText').val();
        
        if (reportMessage) {
            var newReport = { Idea: ideaId, Message: reportMessage}
            
            $.ajax('/api/Reports',
                    {
                        type: 'POST',
                        data: JSON.stringify(newReport),
                        contentType: 'application/json',
                        datatType: 'json'
                    })
                .done(function(data) {
                    closeInputArea();
                    document.getElementById("successMessage").style.display = "block";
                })
                .fail(function() {
                    closeInputArea();
                    document.getElementById("failureMessage").style.display = "block";
                });
        }
    }
    
    function closeInputArea() {
        document.getElementById("reportText").value = "";
        document.getElementById("inputArea").style.display = "none";
        document.getElementById("submitButton").style.display = "none";
    }
    function closeSubmissionMessage() {
        document.getElementById("successMessage").style.display = "none";
        document.getElementById("failureMessage").style.display = "none";
    }
</script>

UI.MVC/Views/Project/Index.cshtml
@model IEnumerable<Domain.Project>

<h1>Projects</h1>

<table class="table">
    <tr>
        <th>
            <p>Name</p>
        </th>
        <th>
            <p>Description</p>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.ActionLink("Questionnaires", "Questionnaires", "Questionnaire"
                    , new { projectId=item.projectId })
            </td>
            <td>
                @Html.ActionLink("Ideations", "Project", "Project"
                    , new { id=item.projectId })
                
            </td>
        </tr>
    }
</table>

UI.MVC/Views/Project/Project.cshtml
@using Domain
@model ProjectAndQuestions


<h2> @Model.project.name</h2>

<table class="table">
    <tr>
        <th>
            <p>Ideation Id </p>
        </th>

        <th>
            <p>Question</p>
        </th>

    </tr>
    @foreach (var item in Model.ideationQuestions)
    {
        
        <tr>
            <td>
                @Html.DisplayFor( modelItem => item.ideation.ideationId)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.question)
            </td>
            <td>
                @Html.ActionLink("Create Idea", "CreateIdeaPage", "Idea"
                    , new { ideationId=item.ideation.ideationId })
            </td>
            
            <td>
                @Html.ActionLink("Ideas", "Ideas", "Project"
                    , new { id=item.ideation.ideationId })
            </td>

        </tr>
    }
</table>

UI.MVC/Views/Project/Projects.cshtml
@model IEnumerable<Domain.Project>

<h1>Projects</h1>



<table class="table">
    <tr>
        <th>
            <p>Name</p>
        </th>
        <th>
            <p>Description</p>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.ActionLink("Questionnaires", "Questionnaires", "Questionnaire"
                    , new { projectId=item.projectId })
            </td>
            <td>
                @Html.ActionLink("Ideations", "Project", "Project"
                    , new { id=item.projectId })

            </td>
        </tr>
    }
</table>