UI.MVC/Controllers/HomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Dynamic;
using System.Linq;
using BL;
using Microsoft.AspNetCore.Mvc;
using D.UI.MVC.Models;
using Domain;
using Microsoft.AspNetCore.Http;

namespace D.UI.MVC.Controllers
{
    public class HomeController : Controller
    {


        public IActionResult Input()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult AboutPage()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

UI.MVC/Controllers/ProjectController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using BL;
using D.UI.MVC.Models;
using Domain;
using Microsoft.AspNetCore.Mvc;

namespace D.UI.MVC.Controllers
{
    public class ProjectController : Controller
    {
        private IProjectManager projectMgr;
        private IIdeationManager ideationMgr;
        
        public ProjectController()
        {
            projectMgr = new ProjectManager();
            ideationMgr = new IdeationManager();
        }
       
        public IActionResult Index()
        {
            IEnumerable<Project> allProjects = projectMgr.getProjects();
            return View(allProjects);
        }

        public IActionResult Project(int id)
        {
            Project p1 = projectMgr.getProject(id);
            IEnumerable<IdeationQuestion> ideationQuestions1 = ideationMgr.GetIdeationQuestionsForProject(id);
            var model = new ProjectAndQuestions() {ideationQuestions = ideationQuestions1, project = p1};

            return View(model);
        }

        public IActionResult Ideas(int id)
        {
            IEnumerable<Idea> ideas = ideationMgr.getIdeas(id);
            return View(ideas);
        }

        public IActionResult MapTest()
        {
            return View();
        }
     
        
        
        
        public ActionResult ImageTest()
        {
            Idea idea = ideationMgr.getIdea(19);
           // Field[] fields = idea.fields.ToArray();
           var fields = idea.fields.ToArray();
           ICollection<ImageField> imageFields = new List<ImageField>();
           
           foreach (var imagefield in fields)
           {
             imageFields.Add((ImageField)imagefield);
           }
          
            return View(imageFields);
        }
    }
}

UI.MVC/Controllers/QuestionnaireController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using BL;
using D.UI.MVC.Models;
using Domain;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuestionUser = Domain.QuestionUser;

namespace D.UI.MVC.Controllers
{
    public class QuestionnaireController : Controller
    {
        private readonly IQuestionnaireManager qmgr;
        private readonly IProjectManager pmgr;

        public QuestionnaireController()
        {
            qmgr = new QuestionnaireManager();
            pmgr = new ProjectManager();
        }
        
        public IActionResult Questionnaires(int projectId)
        {
            IEnumerable<Questionnaire> allQuestionnaires = qmgr.getQuestionnaires(projectId);
            return View(allQuestionnaires);
        }
        
        public IActionResult Questionnaire(int questionnaireId)
        {
            FillInQuestionnaireModel fillInQuestionnaireModel = new FillInQuestionnaireModel();
            fillInQuestionnaireModel.questions = qmgr.getQuestions(questionnaireId);
            fillInQuestionnaireModel.questionnaire = qmgr.getQuestionnaire(questionnaireId);
            return View(fillInQuestionnaireModel);
        }

        public IActionResult CreateQuestionnairePage(int projectId)
        {
            QuestionnaireQuestion combinedModel = new QuestionnaireQuestion();
            combinedModel.projectId = projectId;
            return View(combinedModel);
        }

        public IActionResult ShowResultsPage(int questionnaireId)
        {
            QuestionResultModel combinedModel = new QuestionResultModel();
            IList<QuestionUser> questionUsers = new List<QuestionUser>();
            IList<string> answers = new List<string>();
            IList<Question> ques = new List<Question>();
            IList<OptionsAmount> optionsAmounts = new List<OptionsAmount>();
            combinedModel.questionnaire = qmgr.getQuestionnaire(questionnaireId); 
            
            foreach (var qu in qmgr.getQuestionUsers(questionnaireId))
            {
                questionUsers.Add(qu);
            }

            if (questionUsers.Count == 0)
            {
                return View(combinedModel);
            }
            combinedModel.questionUsers = questionUsers;
            var questionnaireAnswerCount = combinedModel.questionUsers.GroupBy(q => q.Question.id).ToList()[0].Count();
            combinedModel.answeredQuestionAmount = questionnaireAnswerCount;

            foreach (var qu in combinedModel.questionUsers)
            {
                Question q = qu.Question;
                if (q.questionType == QuestionType.DROPDOWN || q.questionType == QuestionType.RADIO_BUTTON)
                {
                    IList<Option> op = qmgr.getOptions(q.id).ToList();
                    foreach (var o in op)
                    {
                        if (o.option == qu.Answer)
                        {
                            answers.Add(o.id + "-" + o.question.id);
                        }
                    }
                }
                if (q.questionType == QuestionType.CHECK_BOX)
                {
                    IList<Option> op = qmgr.getOptions(q.id).ToList();
                    foreach (var o in op)
                    {
                        var parts = qu.Answer.Split(",");
                        foreach (var part in parts)
                        {
                            if (part == o.option)
                            {
                                answers.Add(o.id + "-" + o.question.id);
                            }
                        }
                    }
                }
            }

            foreach (var q in qmgr.getQuestions(questionnaireId))
            {
                if (q.questionType == QuestionType.DROPDOWN || q.questionType == QuestionType.RADIO_BUTTON || q.questionType == QuestionType.CHECK_BOX)
                {
                    foreach (var o in q.options)
                    {
                        q.options.Append(o);
                    }
                    ques.Add(q);
                }
            }
            var amountVotedPerQuestion = answers.GroupBy(o => o);
            foreach (var o in amountVotedPerQuestion)
            {
                var parts = o.Key.Split("-");
                OptionsAmount oa = new OptionsAmount()
                {
                    optionId = Convert.ToInt32(parts[0]),
                    questionId = Convert.ToInt32(parts[1]),
                    count = o.Count()
                };
                optionsAmounts.Add(oa);
            }

            combinedModel.optionsAmounts = optionsAmounts;
            combinedModel.questions = ques;
            
            return View(combinedModel);
        }

        public IActionResult EditQuestionnairePage(int questionnaireId)
        {
            QuestionnaireQuestion combinedModel = new QuestionnaireQuestion();
            combinedModel.questionnaire = qmgr.getQuestionnaire(questionnaireId);
            combinedModel.questions = qmgr.getQuestions(questionnaireId);
            return View(combinedModel);
        }

        public IActionResult DeleteQuestionnairePage(int questionnaireId)
        {
            Questionnaire questionnaire = qmgr.getQuestionnaire(questionnaireId);
            return View(questionnaire);
        }

        [HttpPost]
        public IActionResult EditQuestionnaire(IFormCollection form)
        {
            var oldQuestionnaireId = 0;
            var oldQuestionnaireName = "";
            ICollection<String> questionOptionKey = new List<string>();
            ICollection<String> questionOptionValue = new List<string>();
            
            foreach (var key in form.Keys)
            {
                if (key == "questionnaire.id")
                {
                    oldQuestionnaireId = Convert.ToInt32(form[key]);
                }
            }
            IList<QuestionUser> questionUsers = qmgr.getQuestionUsers(oldQuestionnaireId).ToList();
            foreach (var qu in questionUsers)
            {
                qmgr.removeQuestionUser(qu.id);
            }
            
            ICollection<int> notRemovedQuestionIds = new List<int>();
            Questionnaire oldQuestionnaire = qmgr.getQuestionnaire(oldQuestionnaireId);
            ICollection<Question> oldQuestions = qmgr.getQuestions(oldQuestionnaireId).ToList();

            foreach (var key in form.Keys)
            {
                if (key.StartsWith("question.question"))
                {
                    Question q = new Question()                    
                    {                                              
                        question = "",                      
                        questionnaire = oldQuestionnaire,          
                        questionType = QuestionType.OPEN_QUESTION, 
                        IotSetup = null,                           
                        options = new List<Option>()               
                    };
                    IList<Option> newOptions = new List<Option>();
                    string[] parts = key.Split("-");
                    int optionAmount = 1;
                    foreach (var subKey in form.Keys)
                    {
                        if (subKey == "dynamicFieldset" + parts[1])                                             
                        {        
                            if (form[subKey] == "email") { q.questionType = QuestionType.MAILADDRESS; }       
                            if (form[subKey] == "dropdown") { q.questionType = QuestionType.DROPDOWN; }         
                            if (form[subKey] == "radiobutton") { q.questionType = QuestionType.RADIO_BUTTON; }  
                            if (form[subKey] == "checkbox") { q.questionType = QuestionType.CHECK_BOX; }        
                            if (form[subKey] == "textarea") { q.questionType = QuestionType.OPEN_QUESTION; } 
                        }
                        if (subKey == "question.options-" + optionAmount + "-" + parts[1] + "-0")
                        {
                            Option o = new Option()
                            {
                                option = form[subKey],
                                question = q
                            };
                            newOptions.Add(o);
                            optionAmount++;
                        }
                    }
                    q.question = form[key];
                    qmgr.addQuestion(q);                           
                    qmgr.changeQuestionnaire(oldQuestionnaire);    
                    foreach (var o in newOptions)
                    {
                        qmgr.addOption(o.option, o.question);
                    }
                    q.options = newOptions;
                    qmgr.changeQuestion(q);
                }    
                if (key.StartsWith("question.options-"))         
                {
                    questionOptionKey.Add(key);                  
                    questionOptionValue.Add(form[key]);          
                }
            }
            foreach (var key in form.Keys)
            {
                if (key == "questionnaire.name")
                {
                    oldQuestionnaireName = form[key];
                }
                if (key.StartsWith("question-"))
                {
                    string[] parts = key.Split("-");
                    notRemovedQuestionIds.Add(Convert.ToInt32(parts[1]));
                    int testt = 1;
                    for (var i = 0; i < oldQuestions.Count; i++)
                    {
                        if (Convert.ToInt32(parts[1]) == oldQuestions.ToList()[i].id)
                        {
                            Question q = oldQuestions.ToList()[i];
                            q.question = form[key];

UI.MVC/Views/Home/AboutPage.cshtml
@{
    ViewData["Title"] = "AboutPage";
}

<body>
    <!-- PAGE HEADER -->
    <header id="page-header">
        <div class="container">
            <div class="row">
                <div class="col-md-6 m-auto text-center">
                    <h1>About Us</h1>
                </div>
            </div>
        </div>
    </header>
    <!-- ABOUT SECTION -->
    <section id="about" class="py-3">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h2>What We Do</h2>
                    <p>
                        <b>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, fuga eaque. Amet, assumenda aliquid tempore dolorum
                            error eveniet doloribus sed repellat quod, dolores fuga ipsam soluta. Aliquam accusantium pariatur aut sint deleniti
                            laborum ducimus voluptatem? Architecto cumque quod suscipit officiis soluta, voluptate dicta blanditiis similique
                            praesentium temporibus adipisci debitis labore!
                        </b>
                        <b>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, fuga eaque. Amet, assumenda aliquid tempore dolorum
                            error eveniet doloribus sed repellat quod, dolores fuga ipsam soluta. Aliquam accusantium pariatur aut sint deleniti
                            laborum ducimus voluptatem? Architecto cumque quod suscipit officiis soluta, voluptate dicta blanditiis similique
                            praesentium temporibus adipisci debitis labore!
                        </b>
                    </p>
                </div>
                <div class="col-sm-6">
                    <img src="~/images/ABoutPage1image.jpg" alt="" class="img-fluid rounded-circle d-none d-md-block about-img">
                </div>
            </div>
        </div>

        <section id="Recent" class="p-5">
            <div class="container.flow">
                <div class="row mb-4">
                    <div class="col-md-4">
                        <div class="card bg-info text-white text-center">
                            <div class="card-body">
                                
                                <h3>"Connecting people from all over the country by activities is our Passion"</h3>
                                <i class="fas fa-info"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card bg-dark text-white text-center">
                            <div class="card-body">
                                <h3>"Connecting people from all over the country by activities is our Passion"</h3>
                                <i class="fas fa-info"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card bg-info text-white text-center">
                            <div class="card-body">
                                <h3>"Connecting people from all over the country by activities is our Passion"</h3>
                                <i class="fas fa-info"></i>
                            </div>
                        </div>
                    </div>
                </div>
                    
                </div>
            </div>
        </section>

    </section>
</body>

UI.MVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "";
}
<h2>@ViewData["Title"]</h2>

<body>
    <h2 class="text-center"><b>Project "xxxxxxxxxxx"</b></h2>

    <div class="container">
        <h2>Titel</h2>
        <form action="/action_page.php">
            <div class="form-group">
                <label for="centralevraag">Geef de centrale vraag in:</label>
                <input type="text" class="form-control" id="centralevraag" placeholder="vul in">
            </div>
            <div class="form-group">
                <label for="link">Geef een link naar meer achtergrondinfo:</label>
                <input type="text" class="form-control" id="link" placeholder="vul in">
            </div>
            <div class="form-group">
                <label for="dossier">Geef een korte omschrijving van het dossier:</label>
                <input type="text" class="form-control" id="omschrijving" placeholder="vul in">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>




</body>

UI.MVC/Views/Home/Index.cshtml
<body>

    <section id="showcase">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item carousel-image-1">
                    <div class="container">
                        <div class="carousel-caption d-none d-sm-block text-right mb-5">
                            <h1 class="display-3">PROJECTEN</h1>
                            <p class="lead">
                                Dummy tekst
                            </p>
                            
                        </div>
                    </div>
                </div>

                <div class="carousel-item carousel-image-2">
                    <div class="container">
                        <div class="carousel-caption d-none d-sm-block text-right mb-5">
                            <h1 class="display-3">Projecten</h1>
                            <p class="lead">
                                Doe mee!
                            </p>
                           
                        </div>
                    </div>
                </div>

                <div class="carousel-item carousel-image-3 active">
                    <div class="container">
                        <div class="carousel-caption d-none d-sm-block text-right mb-5">
                            <h1 class="display-3">ACTIVITEITEN</h1>
                            <p class="lead">
                                Dummy tekst
                            </p>
                            
                        </div>
                    </div>
                </div>
            </div>

            <a href="#myCarousel" data-slide="prev" class="carousel-control-prev">
                <span class="carousel-control-prev-icon"></span>
            </a>

            <a href="#myCarousel" data-slide="next" class="carousel-control-next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </section>

    <!-- HOME SECTION -->

    <div class="container">
        <div class="row">
            <div class="col text-center py-5">
                <h1 class="text-white">Welkom!</h1>
                <h3 class="text-white">

                    Wij van treecompany hebben dit platform ontworpen zodat burgers hun opinie's en ideeen kunnen geven over projecten
                    die in hun omgeving verwezenlijkt zullen worden. Want elke stem telt!

                </h3>
                <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">
                    Aanmelden
                </button>
            </div>

            <div class="container">
   
                <div class="modal" id="myModal">
                    <div class="modal-dialog modal-sm bg-dark">
                        <div class="modal-content bg-dark">

                            <div class="card bg-dark card-form">
                                <div class="card-body bg-dark">
                                    <h3 class="text-white"><u>Aanmelden</u></h3>
                                    <form>
                                        <div class="form-group">
                                            <input type="email"
                                                   class="form-control form-control-lg"
                                                   placeholder="Email" />
                                        </div>
                                        <div class="form-group">
                                            <input type="password"
                                                   class="form-control form-control-lg"
                                                   placeholder="Wachtwoord" />
                                        </div>

                                        <button type="submit" class="btn btn-primary">Inloggen</button>

                                        <div class="d-flex justify-content-center mb-3">
                                            <div class="p-2"> <i class="fab fa-google"></i></div>

                                            <div class="p-2"> <i class="fab fa-facebook-f"></i></div>

                                        </div>
                                        <div class="d-flex flex-column mb-3">
                                            <div class="p-2">Registreren</div>
                                            <div class="p-2">Wachtwoord Vergeten?</div>
                                        </div>



                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>


    <!-- Projects HEAD -->
    <section id="projects-head-section">
        <div class="container">
            <div class="row">
                <div class="col text-center py-5">
                    <h1 class="text-white">Onze Projecten</h1>
                    <h4 class="text-white">

                        Heb je interesse om meer te leren over de vele projecten in jouw
                        buurt, dan moet je niet verder zoeken.
                    </h4>
                    <div class="col text-center">
                        <a asp-controller="Project" asp-action="Index" class="btn btn-success btn-lg">Meer info</a>


                    </div>
                </div>
            </div>
        </div>
    </section>


    <!-- Explorer Section -->
    <section id="explore-section">
        <div class="row">
            <div class="column">
                <img src="~/images/park1.jpg" alt="Snow" style="width:100%">
                <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:40%"></div>
                </div>
                <div>
                    <p>
                        <i class="far fa-heart"></i> 5
                        <i class="far fa-comments"></i> 6
                        <i class="fas fa-share-alt"></i> 8
                    </p>

                </div>
            </div>
            <div class="column">
                <img src="~/images/straat2.jpg" alt="Forest" style="width:100%">
                <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:40%"></div>
                </div>
                <div>
                    <p>
                        <i class="far fa-heart"></i> 5
                        <i class="far fa-comments"></i> 6
                        <i class="fas fa-share-alt"></i> 8
                    </p>
                </div>
            </div>
            <div class="column">
                <img src="~/images/building3.jpg" alt="Mountains" style="width:100%">
                <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:40%"></div>
                </div>
                <div>
                    <p>
                        <i class="far fa-heart"></i> 5
                        <i class="far fa-comments"></i> 6
                        <i class="fas fa-share-alt"></i> 8
                    </p>

                </div>


            </div>

            <div class="col text-center">
                <a asp-action="About" class="btn btn-success btn-lg">Ontdek meer</a>
            </div>
        


        </div>


    </section>

    <div class="col text-center py-5">
        <h2 class="text-white">Recente Acticiteiten</h2>
    </div>

    <section id="Recent" class="p-5">
        <div class="container.flow">
            <div class="row mb-4">
                <div class="col-md-4">
                    <div class="card bg-info text-white text-center">
                        <div class="card-body">
                            <img class="card-img-top" src="~/images/person.png" alt="Card image" style="width:20%">
                            <h3>"Naam"</h3>
                            Deze persoon heeft gereageerd op.....
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card bg-dark text-white text-center">
                        <div class="card-body">
                            <img class="card-img-top" src="~/images/person.png" alt="Card image" style="width:20%">
                            <h3>"Naam"</h3>
                            Deze persoon heeft gereageerd op.....
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card bg-info text-white text-center">
                        <div class="card-body">
                            <img class="card-img-top" src="~/images/person.png" alt="Card image" style="width:20%">
                            <h3>"Naam"</h3>
                            Deze persoon heeft gereageerd op.....
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mb-4">
                <div class="col-md-4">
                    <div class="card bg-dark text-white text-center">
                        <div class="card-body">
                            <img class="card-img-top" src="~/images/person.png" alt="Card image" style="width:20%">
                            <h3>"Naam"</h3>
                            Deze persoon heeft gereageerd op.....
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card bg-info text-white text-center">
                        <div class="card-body">
                            <img class="card-img-top" src="~/images/person.png" alt="Card image" style="width:20%">
                            <h3>"Naam"</h3>
                            Deze persoon heeft gereageerd op.....
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card bg-dark text-white text-center">
                        <div class="card-body">
                            <img class="card-img-top" src="~/images/person.png" alt="Card image" style="width:20%">
                            <h3>"Naam"</h3>
                            Deze persoon heeft gereageerd op.....
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>






    <script src="http://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
            integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
            crossorigin="anonymous"></script>


</body>

UI.MVC/Views/Home/Input.cshtml
@page
@model D.UI.MVC.Views.Home.Input

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    <form>
        <input type="text" name="beschrijving" />
        <input type="text" name="amount" />
        <input type="submit" /> 
    </form>
</div>
</body>
</html>

UI.MVC/Views/Home/Questionnaires.cshtml
@model IEnumerable<Domain.Questionnaire>

<h1>Questionnaires</h1>

<table class="table">
    <tr>
        <th>
            <p>name</p>
        </th>
        <th>
            <p>Amount of questions</p>
        </th>
    </tr>
    @foreach (var item in Model)
    {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.questionAmount)
                </td>
                <td>
                    @Html.ActionLink("Complete Questionnaire", "Questionnaire", "Home"
                        , new { id=item.id })
                </td>
            </tr>
        
    }
</table>